# Generated by Django 5.2.9 on 2026-06-22 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_responsible_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['request_status', '-created_at'], name='req_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['assigned_manager', '-created_at'], name='req_manager_created_idx'),
        ),
    ]
