# Generated by Django 5.2.9 on 2026-06-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_request_req_status_created_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='request',
            name='req_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='req_manager_created_idx',
        ),
    ]
